#!/usr/bin/env python3
DEBUG_MODE = True
class ModelConstants:
    time = Any
    lo = Any

    def __init__(self):
        self.lo = "nothin"


    @staticmethod
    def add_element(x):
        ModelConstants.time = x



